Añadiendo filtro por fecha desde consulta a data base. Resolviendo #53
edwin-navarrete/cybersec_album pull request #57
Opened 2023-05-15 17:11 UTC by jcalderonagudelo

Se añade filtro por fecha desde una consulta modificada, se eliminaron los filtros que se realizaban en el frontEnd. Se resuelve la issue #53

2023-05-16 16:06 UTC, edwin-navarrete requested changes
Por favor aplicar los cambios requeridos

2023-05-16 16:06 UTC, edwin-navarrete commented on statServer/app.ts
> +app.use("/ranking2", filterByDateRouter)
No debería haber un ranking2, sólo debe existir ranking, elimínalo por favor

2023-05-16 16:06 UTC, edwin-navarrete commented on statClient/src/components/table.tsx
> +      .get(`http://localhost:8001/ranking`)
No usemos `` si no hay variables para reemplazar en la cadena. Usa comilla sencilla ' por favor

2023-05-16 16:06 UTC, edwin-navarrete commented on statClient/src/components/table.tsx
> +      .get(`http://localhost:8001/ranking2?date=${new Date(date.valueOf()).toLocaleDateString('es-ES')}`)//Url api server
La url del servicio (incluyendo el puerto es decir http://localhost:8001) debe ser provista por una variable de ambiente, no puede estar en hardcode

2023-05-22 03:29 UTC, jcalderonagudelo commented
Por favor revisar si quedaron hechas correctamente las correcciones.

2023-05-24 22:35 UTC, edwin-navarrete approved these changes

2023-05-24 22:36 UTC, merged