Resolviendo issue número #54 se necesitan la metadata de las preguntas en la bd
edwin-navarrete/cybersec_album pull request #60
Opened 2023-06-01 22:37 UTC by jcalderonagudelo

2023-06-04 16:58 UTC, edwin-navarrete requested changes

2023-06-04 16:58 UTC, edwin-navarrete commented on db_schema/ssolucio_cyberalbum.sql
> +  feedback TEXT,
Elimina la coma al final de esta línea

2023-06-04 16:58 UTC, edwin-navarrete commented on db_schema/ssolucio_cyberalbum.sql
> +WHERE id = <id_de_la_pregunta>;
Por favor elimina esta sentencia.

2023-06-05 00:23 UTC, jcalderonagudelo commented on db_schema/ssolucio_cyberalbum.sql
> +  feedback TEXT,
Cambios realizados

2023-06-05 00:23 UTC, jcalderonagudelo commented on db_schema/ssolucio_cyberalbum.sql
> +WHERE id = <id_de_la_pregunta>;
Cambios realizados

2023-06-06 01:32 UTC, edwin-navarrete approved these changes

2023-06-06 01:32 UTC, merged