Creacion de vista respuestas
edwin-navarrete/cybersec_album pull request #80
Opened 2024-02-17 19:29 UTC by camartinezm92

Se genera vista de respuestas, se crea ingreso desde menú lateral, se filtra por fechas desde y hasta, se pueden ordenar datos de forma ascendente o descendente, verificar funcionalidad y la vista, unica novedad el dato de tiempo promedio no logro realizarle una adecuada lectura, me podrias brindar una guia, 

gracias!

2024-02-24 19:59 UTC, edwin-navarrete requested changes
Ya revise el código, resolví el error "" y el problema de ordenamiento, que era porque el driver de mysql en el lado del servidor retorna los floats como strings.  Necesito por favor los siguientes cambios:

- El menú que dice: Estadisticas, Configuracion, Respuestas, Reorganicémolo así: Tabla de Clasificación, Desempeño de Preguntas
- En vez del título "Tabla de Clasificación de preguntas" debe decir "Desempeño de Preguntas"
- Las flechas de ordenamiento están alreves si apunta hacia arriba el orden debe ser ascendente, si apunta hacia abajo lo contrario
- En vez de "Numero de veces que se ha intentado la pregunta" "Número de Intentos"

2024-02-24 19:59 UTC, edwin-navarrete commented on statClient/src/components/tableAswers.tsx
> +interface IAnswerData {
Reemplazar por IQuestionData

2024-02-24 19:59 UTC, edwin-navarrete commented on statClient/src/components/tableAswers.tsx
> +export default function AnswersTable() {
Cambiar por QuestionPerformanceTable, igual el nombre del archivo

2024-03-02 21:41 UTC, camartinezm92 commented on statClient/src/components/tableAswers.tsx
> +interface IAnswerData {
![cambio menu lateral](https://github.com/edwin-navarrete/cybersec_album/assets/111545537/726f8b7d-d853-4f65-a5de-39e4485666d3)
![cambios solicitados](https://github.com/edwin-navarrete/cybersec_album/assets/111545537/b1058501-2746-4d02-bd22-8ddeb63f94c6)


se realizan los cvambio solicitados, para verificacion.

2024-03-02 21:41 UTC, camartinezm92 commented
Se realizan cambio solicitados se anexa evidencia y se actualiza la rama para validacion.
![cambios solicitados](https://github.com/edwin-navarrete/cybersec_album/assets/111545537/0287754d-b672-4149-9b08-5810ccfd983f)
![cambio menu lateral](https://github.com/edwin-navarrete/cybersec_album/assets/111545537/3062c67d-24d2-4f63-9694-e9ff7bd25128)

2024-04-18 14:01 UTC, edwin-navarrete approved these changes

2024-04-18 14:01 UTC, merged